#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

nj=15

# Default flow starts from manifest preparation and stops after feature extraction.
# Stage 0 (download) is skipped because download/ is already symlinked.
# Stage 2 and stage 7 prepare MUSAN assets, which are disabled for this recipe.
# Stage 5-6 split and recompute the M subset; the Zipformer M recipe consumes
# data/fbank/gigaspeech_cuts_M.jsonl.gz directly, so those stages are opt-in only.
# Stage 8 prepares BPE and is typically run separately or replaced with a symlink.
stage=1
stop_stage=4
cpu_only=false
stage4_num_workers=32
stage4_batch_duration=1000

# Compute fbank features for a subset of splits from `start` (inclusive) to `stop` (exclusive)
start=0
stop=-1  # -1 means until the end

# Note: This script just prepares the minimal requirements needed by a
# transducer training with bpe units.
#
# If you want to use ngram, please continue running prepare_lm.sh after
# you succeed in running this script.
#
# This script also contains the steps to generate phone based units, but they
# will not run automatically, you can generate the phone based units by
# bash prepare.sh --stage 9 --stop-stage 9

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/GigaSpeech
#      You can find audio, dict, GigaSpeech.json inside it.
#      You can apply for the download credentials by following
#      https://github.com/SpeechColab/GigaSpeech#download
#
#  - $dl_dir/lm
#      This directory contains the language model downloaded from
#        https://huggingface.co/wgb14/gigaspeech_lm
#
#        - 3gram_pruned_1e7.arpa.gz
#        - 4gram.arpa.gz
#        - lexicon.txt
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#       - music
#       - noise
#       - speech

data_root=data
download_dir=download

resolve_path() {
  local path="$1"
  if [[ "$path" = /* ]]; then
    printf "%s\n" "$path"
  else
    printf "%s\n" "${script_dir}/${path}"
  fi
}

. "${script_dir}/shared/parse_options.sh" || exit 1

data_root="$(resolve_path "${data_root}")"
dl_dir="$(resolve_path "${download_dir}")"
manifest_dir="${data_root}/manifests"
fbank_dir="${data_root}/fbank"
feature_split_dir="${fbank_dir}/gigaspeech_M_split"
preprocess_stamp="${fbank_dir}/.preprocess_complete"

cd "${script_dir}"

# vocab size for sentence piece models.
# It will generate data/lang_bpe_xxx,
# data/lang_bpe_yyy if the array contains xxx, yyy
vocab_sizes=(
  # 5000
  # 2000
  # 1000
  500
)

# All files generated by this script are saved in "${data_root}".
# You can safely remove it and rerun this script to regenerate it.
mkdir -p "${data_root}"

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"

log "dl_dir: $dl_dir"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download LM"
  # We assume that you have installed the git-lfs, if not, you could install it
  # using: `sudo apt-get install git-lfs && git-lfs install`
  [ ! -e $dl_dir/lm ] && mkdir -p $dl_dir/lm
  git clone https://huggingface.co/wgb14/gigaspeech_lm $dl_dir/lm
  gunzip -c $dl_dir/lm/3gram_pruned_1e7.arpa.gz > $dl_dir/lm/3gram_pruned_1e7.arpa
  gunzip -c $dl_dir/lm/4gram.arpa.gz > $dl_dir/lm/4gram.arpa
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  [ ! -e $dl_dir/GigaSpeech ] && mkdir -p $dl_dir/GigaSpeech

  # If you have pre-downloaded it to /path/to/GigaSpeech,
  # you can create a symlink
  #
  #   ln -svf /path/to/GigaSpeech $dl_dir/GigaSpeech
  #
  if [ ! -d $dl_dir/GigaSpeech/audio ] && [ ! -f $dl_dir/GigaSpeech.json ]; then
    # Check credentials.
    if [ ! -f $dl_dir/password ]; then
      echo -n "$0: Please apply for the download credentials by following"
      echo -n "https://github.com/SpeechColab/GigaSpeech#download"
      echo " and save it to $dl_dir/password."
      exit 1;
    fi

    PASSWORD=`cat $dl_dir/password 2>/dev/null`
    if [ -z "$PASSWORD" ]; then
      echo "$0: Error, $dl_dir/password is empty."
      exit 1;
    fi

    PASSWORD_MD5=`echo $PASSWORD | md5sum | cut -d ' ' -f 1`
    if [[ $PASSWORD_MD5 != "dfbf0cde1a3ce23749d8d81e492741b8" ]]; then
      echo "$0: Error, invalid $dl_dir/password."
      exit 1;
    fi

    # Download XL, DEV and TEST sets by default.
    # Support hosts:
    # 1. oss
    # 2. tsinghua
    # 3. speechocean
    # 4. magicdata
    lhotse download gigaspeech \
      --host magicdata \
      --subset DEV \
      --subset TEST \
      --subset XL \
      $dl_dir/password $dl_dir/GigaSpeech
  fi

  # If you have pre-downloaded it to /path/to/musan,
  # you can create a symlink
  #
  #   ln -svf /path/to/musan $dl_dir/
  #
  if [ ! -d $dl_dir/musan ]; then
    lhotse download musan $dl_dir
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare GigaSpeech manifest (may take 15 minutes)"
  # We assume that you have downloaded the GigaSpeech corpus
  # to $dl_dir/GigaSpeech
  mkdir -p "${manifest_dir}"
  lhotse prepare gigaspeech \
    --subset M \
    --subset DEV \
    --subset TEST \
    -j $nj \
    "$dl_dir/GigaSpeech" "$manifest_dir"
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Prepare musan manifest"
  # We assume that you have downloaded the musan corpus
  # to $dl_dir/musan
  mkdir -p "${manifest_dir}"
  lhotse prepare musan "$dl_dir/musan" "$manifest_dir"
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "State 3: Preprocess GigaSpeech manifest"
  mkdir -p "${fbank_dir}"
  if [ ! -f "${preprocess_stamp}" ]; then
    python3 ./local/preprocess_gigaspeech.py \
      --manifest-dir "${manifest_dir}" \
      --output-dir "${fbank_dir}" \
      --cpu-only "${cpu_only}"
    touch "${preprocess_stamp}"
  fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Compute Kaldifeat fbank features for DEV, TEST, and M."
  python3 ./local/compute_fbank_gigaspeech.py \
    --fbank-dir "${fbank_dir}" \
    --num-workers "${stage4_num_workers}" \
    --batch-duration "${stage4_batch_duration}"
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 5: Split M subset into pieces (may take 5 minutes)"
  num_per_split=50
  split_dir="${feature_split_dir}"
  if [ ! -f $split_dir/.split_completed ]; then
    lhotse split-lazy "${fbank_dir}/gigaspeech_cuts_M_raw.jsonl.gz" "$split_dir" "$num_per_split"
    touch $split_dir/.split_completed
  fi
fi

if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
  log "Stage 6: Compute features for M"
  split_dir="${feature_split_dir}"
  num_splits=$(find $split_dir -name "gigaspeech_cuts_M_raw.*.jsonl.gz" | wc -l)
  python3 ./local/compute_fbank_gigaspeech_splits.py \
    --split-dir "${split_dir}" \
    --num-workers 20 \
    --batch-duration 600 \
    --num-splits $num_splits \
    --start $start \
    --stop $stop
fi

if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
  log "Stage 7: Compute fbank for musan"
  mkdir -p "${fbank_dir}"
  ./local/compute_fbank_musan.py \
    --manifest-dir "${manifest_dir}" \
    --output-dir "${fbank_dir}"
fi

if [ $stage -le 8 ] && [ $stop_stage -ge 8 ]; then
  log "Stage 8: Prepare BPE based lang"
  for vocab_size in ${vocab_sizes[@]}; do
    lang_dir="${data_root}/lang_bpe_${vocab_size}"
    mkdir -p "$lang_dir"

    if [ ! -s "$lang_dir/transcript_words.txt" ]; then
      log "Generate data for BPE training"
      if command -v jq >/dev/null 2>&1; then
        gunzip -c "${manifest_dir}/gigaspeech_supervisions_M.jsonl.gz" \
          | jq '.text' \
          | sed 's/"//g' \
          > "$lang_dir/transcript_words.txt"
      else
        MANIFEST_DIR="${manifest_dir}" python3 - <<'PY' > "$lang_dir/transcript_words.txt"
import gzip
import json
import os

with gzip.open(
    os.path.join(os.environ["MANIFEST_DIR"], "gigaspeech_supervisions_M.jsonl.gz"),
    "rt",
) as f:
    for line in f:
        obj = json.loads(line)
        print(obj["text"])
PY
      fi

      # Delete utterances with garbage meta tags
      garbage_utterance_tags="<SIL> <MUSIC> <NOISE> <OTHER>"
      for tag in $garbage_utterance_tags; do
        sed -i "/${tag}/d" "$lang_dir/transcript_words.txt"
      done

      # Delete punctuations in utterances
      punctuation_tags="<COMMA> <EXCLAMATIONPOINT> <PERIOD> <QUESTIONMARK>"
      for tag in $punctuation_tags; do
        sed -i "s/${tag}//g" "$lang_dir/transcript_words.txt"
      done

      # Ensure space only appears once
      sed -i 's/\t/ /g' "$lang_dir/transcript_words.txt"
      sed -i 's/[ ][ ]*/ /g' "$lang_dir/transcript_words.txt"
    fi

    if [ ! -f "$lang_dir/bpe.model" ]; then
      ./local/train_bpe_model.py \
        --lang-dir "$lang_dir" \
        --vocab-size "$vocab_size" \
        --transcript "$lang_dir/transcript_words.txt"
    fi
  done
fi

if [ $stage -le 9 ] && [ $stop_stage -ge 9 ]; then
  log "Stage 9: Prepare phone based lang"
  lang_dir="${data_root}/lang_phone"
  mkdir -p "$lang_dir"

  (echo '!SIL SIL'; echo '<SPOKEN_NOISE> SPN'; echo '<UNK> SPN'; ) |
    cat - "$dl_dir/lm/lexicon.txt" |
    sort | uniq > "$lang_dir/lexicon.txt"

  if [ ! -f "$lang_dir/L_disambig.pt" ]; then
    ./local/prepare_lang.py --lang-dir "$lang_dir"
  fi
fi
