#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -euo pipefail

nj=15

# Default flow starts from manifest preparation and stops after the main 24k
# features are ready. Stage 0 (download) is skipped because download/ is
# typically symlinked. Stage 2 and stage 9 prepare MUSAN assets, which are
# disabled for this recipe by default. Stage 7-8 split and recompute the M
# subset, so they remain opt-in for the main Zipformer path. Stage 10 prepares
# BPE and is typically run separately.
stage=1
stop_stage=6
cpu_only=false

# Backward-compatible options for the main feature extraction stage.
stage4_num_workers=32
stage4_batch_duration=1000

recording_num_splits=1000
resample_start=0
resample_stop=-1
resample_num_workers=32
target_sample_rate=24000
use_resampled_audio=true

# Backward-compatible options for split feature extraction.
num_splits=100
start=0
stop=-1
feature_num_splits=""
feature_start=""
feature_stop=""
feature_num_workers=""
feature_batch_duration=""

# Note: This script just prepares the minimal requirements needed by a
# transducer training with bpe units.
#
# If you want to use ngram, please continue running prepare_lm.sh after
# you succeed in running this script.
#
# This script also contains the steps to generate phone based units, but they
# will not run automatically, you can generate the phone based units by
# bash prepare.sh --stage 11 --stop-stage 11

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/GigaSpeech
#      You can find audio, dict, GigaSpeech.json inside it.
#      You can apply for the download credentials by following
#      https://github.com/SpeechColab/GigaSpeech#download
#
#  - $dl_dir/lm
#      This directory contains the language model downloaded from
#        https://huggingface.co/wgb14/gigaspeech_lm
#
#        - 3gram_pruned_1e7.arpa.gz
#        - 4gram.arpa.gz
#        - lexicon.txt
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#       - music
#       - noise
#       - speech

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

if [ -z "${feature_num_splits}" ]; then
  feature_num_splits=$num_splits
fi
if [ -z "${feature_start}" ]; then
  feature_start=$start
fi
if [ -z "${feature_stop}" ]; then
  feature_stop=$stop
fi
if [ -z "${feature_num_workers}" ]; then
  feature_num_workers=$stage4_num_workers
fi
if [ -z "${feature_batch_duration}" ]; then
  feature_batch_duration=$stage4_batch_duration
fi

# vocab size for sentence piece models.
# It will generate data/lang_bpe_xxx,
# data/lang_bpe_yyy if the array contains xxx, yyy
vocab_sizes=(
  # 5000
  # 2000
  # 1000
  500
)

manifest_dir=data/manifests
resampled_manifest_dir=data/manifests_resampled/${target_sample_rate}
fbank_dir=data/fbank
recording_split_dir=${manifest_dir}/recordings_M_split_${recording_num_splits}
resampled_recording_split_dir=${resampled_manifest_dir}/recordings_M_split_${recording_num_splits}
feature_split_dir=${fbank_dir}/gigaspeech_M_split
resample_cache_dir=data/audio_cache/gigaspeech
preprocess_mode="original"
if [ "${use_resampled_audio}" = true ]; then
  preprocess_mode="resampled_${target_sample_rate}"
fi
preprocess_stamp=${fbank_dir}/.preprocess_complete.${preprocess_mode}
feature_stamp=${fbank_dir}/.features_complete.${preprocess_mode}

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh"
log "dl_dir: $dl_dir"
log "recording_num_splits: $recording_num_splits"
log "target_sample_rate: $target_sample_rate"
log "use_resampled_audio: $use_resampled_audio"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download LM"
  [ ! -e "$dl_dir/lm" ] && mkdir -p "$dl_dir/lm"
  git clone https://huggingface.co/wgb14/gigaspeech_lm "$dl_dir/lm"
  gunzip -c "$dl_dir/lm/3gram_pruned_1e7.arpa.gz" > "$dl_dir/lm/3gram_pruned_1e7.arpa"
  gunzip -c "$dl_dir/lm/4gram.arpa.gz" > "$dl_dir/lm/4gram.arpa"
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  [ ! -e "$dl_dir/GigaSpeech" ] && mkdir -p "$dl_dir/GigaSpeech"

  if [ ! -d "$dl_dir/GigaSpeech/audio" ] && [ ! -f "$dl_dir/GigaSpeech.json" ]; then
    if [ ! -f "$dl_dir/password" ]; then
      echo -n "$0: Please apply for the download credentials by following"
      echo -n "https://github.com/SpeechColab/GigaSpeech#download"
      echo " and save it to $dl_dir/password."
      exit 1
    fi

    PASSWORD=$(cat "$dl_dir/password" 2>/dev/null)
    if [ -z "$PASSWORD" ]; then
      echo "$0: Error, $dl_dir/password is empty."
      exit 1
    fi

    PASSWORD_MD5=$(echo "$PASSWORD" | md5sum | cut -d ' ' -f 1)
    if [[ $PASSWORD_MD5 != "dfbf0cde1a3ce23749d8d81e492741b8" ]]; then
      echo "$0: Error, invalid $dl_dir/password."
      exit 1
    fi

    lhotse download gigaspeech \
      --host magicdata \
      --subset DEV \
      --subset TEST \
      --subset XL \
      "$dl_dir/password" "$dl_dir/GigaSpeech"
  fi

  if [ ! -d "$dl_dir/musan" ]; then
    lhotse download musan "$dl_dir"
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare GigaSpeech manifests (may take 15 minutes)"
  mkdir -p "$manifest_dir"
  lhotse prepare gigaspeech \
    --subset M \
    --subset DEV \
    --subset TEST \
    -j "$nj" \
    "$dl_dir/GigaSpeech" "$manifest_dir"
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Prepare musan manifest"
  mkdir -p "$manifest_dir"
  lhotse prepare musan "$dl_dir/musan" "$manifest_dir"
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Split GigaSpeech M recordings into ${recording_num_splits} shards"
  if [ ! -f "${manifest_dir}/gigaspeech_recordings_M.jsonl.gz" ]; then
    echo "$0: Missing ${manifest_dir}/gigaspeech_recordings_M.jsonl.gz. Run stage 1 first."
    exit 1
  fi
  if [ ! -f "${recording_split_dir}/.split_completed" ]; then
    mkdir -p "$recording_split_dir"
    lhotse split \
      "$recording_num_splits" \
      "${manifest_dir}/gigaspeech_recordings_M.jsonl.gz" \
      "$recording_split_dir"
    touch "${recording_split_dir}/.split_completed"
  fi
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  if [ "${use_resampled_audio}" = false ]; then
    log "Stage 4: Skipping offline resampling because use_resampled_audio=false"
  else
    log "Stage 4: Offline resample recordings to ${target_sample_rate} Hz"
    mkdir -p "$resampled_manifest_dir" "$resampled_recording_split_dir" "$resample_cache_dir"

    if [ ! -d "$recording_split_dir" ]; then
      echo "$0: Missing recording split dir ${recording_split_dir}. Run stage 3 first."
      exit 1
    fi

    if [ "$resample_start" -eq 0 ]; then
      for partition in DEV TEST; do
        python3 ./local/resample_recordings_to_flac.py \
          --input-manifest "${manifest_dir}/gigaspeech_recordings_${partition}.jsonl.gz" \
          --output-manifest "${resampled_manifest_dir}/gigaspeech_recordings_${partition}.jsonl.gz" \
          --source-root "$dl_dir/GigaSpeech" \
          --cache-root "$resample_cache_dir" \
          --target-sample-rate "$target_sample_rate" \
          --num-workers "$resample_num_workers"
      done
    else
      log "Stage 4: resample_start=${resample_start}, skipping DEV/TEST resampling on this worker"
    fi

    mapfile -t recording_shards < <(
      find "$recording_split_dir" -maxdepth 1 -name "gigaspeech_recordings_M.*.jsonl.gz" | sort
    )
    if [ ${#recording_shards[@]} -eq 0 ]; then
      echo "$0: No M recording shards found in ${recording_split_dir}"
      exit 1
    fi

    total_recording_shards=${#recording_shards[@]}
    if [ "$resample_stop" -lt "$resample_start" ]; then
      resample_stop="$total_recording_shards"
    fi
    if [ "$resample_stop" -gt "$total_recording_shards" ]; then
      resample_stop="$total_recording_shards"
    fi

    for ((i=resample_start; i<resample_stop; ++i)); do
      shard_path="${recording_shards[$i]}"
      shard_name=$(basename "$shard_path")
      python3 ./local/resample_recordings_to_flac.py \
        --input-manifest "$shard_path" \
        --output-manifest "${resampled_recording_split_dir}/${shard_name}" \
        --source-root "$dl_dir/GigaSpeech" \
        --cache-root "$resample_cache_dir" \
        --target-sample-rate "$target_sample_rate" \
        --num-workers "$resample_num_workers"
    done
  fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 5: Preprocess GigaSpeech manifests and build raw cuts"
  mkdir -p "$fbank_dir"
  if [ ! -f "$preprocess_stamp" ]; then
    recordings_manifest_args=()
    if [ "${use_resampled_audio}" = true ]; then
      recordings_manifest_args+=(--recordings-manifest-dir "$resampled_manifest_dir")
    fi
    python3 ./local/preprocess_gigaspeech.py \
      --manifest-dir "$manifest_dir" \
      --output-dir "$fbank_dir" \
      --cpu-only "${cpu_only}" \
      "${recordings_manifest_args[@]}"
    touch "$preprocess_stamp"
    touch "${fbank_dir}/.preprocess_complete"
  else
    log "Stage 5: ${preprocess_stamp} exists - skipping"
  fi
fi

if [ $stage -le 6 ] && [ $stop_stage -ge 6 ]; then
  log "Stage 6: Compute 24k features for DEV, TEST, and M"
  mkdir -p "$fbank_dir"
  if [ ! -f "$feature_stamp" ]; then
    python3 ./local/compute_fbank_gigaspeech.py \
      --num-workers "${feature_num_workers}" \
      --batch-duration "${feature_batch_duration}" \
      --overwrite true
    touch "$feature_stamp"
  else
    log "Stage 6: ${feature_stamp} exists - skipping"
  fi
fi

if [ $stage -le 7 ] && [ $stop_stage -ge 7 ]; then
  log "Stage 7: Split M subset into ${feature_num_splits} pieces"
  split_stamp="${feature_split_dir}/.split_completed.${feature_num_splits}"
  if [ ! -f "$split_stamp" ]; then
    mkdir -p "$feature_split_dir"
    lhotse split \
      "$feature_num_splits" \
      "${fbank_dir}/gigaspeech_cuts_M_raw.jsonl.gz" \
      "$feature_split_dir"
    touch "$split_stamp"
  fi
fi

if [ $stage -le 8 ] && [ $stop_stage -ge 8 ]; then
  log "Stage 8: Compute features for split M manifests"
  if [ ! -d "$feature_split_dir" ]; then
    echo "$0: Missing split dir ${feature_split_dir}. Run stage 7 first."
    exit 1
  fi

  num_feature_splits=$(find "$feature_split_dir" -maxdepth 1 -name "gigaspeech_cuts_M_raw.*.jsonl.gz" | wc -l)
  python3 ./local/compute_fbank_gigaspeech_splits.py \
    --num-workers "${feature_num_workers}" \
    --batch-duration "${feature_batch_duration}" \
    --num-splits "$num_feature_splits" \
    --start "$feature_start" \
    --stop "$feature_stop" \
    --overwrite true
fi

if [ $stage -le 9 ] && [ $stop_stage -ge 9 ]; then
  log "Stage 9: Compute fbank for musan"
  mkdir -p "$fbank_dir"
  ./local/compute_fbank_musan.py
fi

if [ $stage -le 10 ] && [ $stop_stage -ge 10 ]; then
  log "Stage 10: Prepare BPE based lang"
  for vocab_size in ${vocab_sizes[@]}; do
    lang_dir=data/lang_bpe_${vocab_size}
    mkdir -p "$lang_dir"

    if [ ! -f "$lang_dir/transcript_words.txt" ]; then
      log "Generate data for BPE training"
      if command -v jq >/dev/null 2>&1; then
        gunzip -c "${manifest_dir}/gigaspeech_supervisions_M.jsonl.gz" \
          | jq '.text' \
          | sed 's/"//g' \
          > "$lang_dir/transcript_words.txt"
      else
        python3 - <<'PY' > "$lang_dir/transcript_words.txt"
import gzip
import json

with gzip.open("data/manifests/gigaspeech_supervisions_M.jsonl.gz", "rt") as f:
    for line in f:
        obj = json.loads(line)
        print(obj["text"])
PY
      fi

      garbage_utterance_tags="<SIL> <MUSIC> <NOISE> <OTHER>"
      for tag in $garbage_utterance_tags; do
        sed -i "/${tag}/d" "$lang_dir/transcript_words.txt"
      done

      punctuation_tags="<COMMA> <EXCLAMATIONPOINT> <PERIOD> <QUESTIONMARK>"
      for tag in $punctuation_tags; do
        sed -i "s/${tag}//g" "$lang_dir/transcript_words.txt"
      done

      sed -i 's/\t/ /g' "$lang_dir/transcript_words.txt"
      sed -i 's/[ ][ ]*/ /g' "$lang_dir/transcript_words.txt"
    fi

    if [ ! -f "$lang_dir/bpe.model" ]; then
      ./local/train_bpe_model.py \
        --lang-dir "$lang_dir" \
        --vocab-size "$vocab_size" \
        --transcript "$lang_dir/transcript_words.txt"
    fi
  done
fi

if [ $stage -le 11 ] && [ $stop_stage -ge 11 ]; then
  log "Stage 11: Prepare phone based lang"
  lang_dir=data/lang_phone
  mkdir -p "$lang_dir"

  (echo '!SIL SIL'; echo '<SPOKEN_NOISE> SPN'; echo '<UNK> SPN'; ) \
    | cat - "$dl_dir/lm/lexicon.txt" \
    | sort | uniq > "$lang_dir/lexicon.txt"

  if [ ! -f "$lang_dir/L_disambig.pt" ]; then
    ./local/prepare_lang.py --lang-dir "$lang_dir"
  fi
fi

log "prepare.sh: DONE"
